version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    ports:
      - "4000:4000"
    environment:
      - PG_DB=express_db
      - PG_USER=express_user
      - PG_PASSWORD=12345
      - PG_HOST=pg_db
      - PORT=4000
      - SECRET_JWT_SEED=MY_SECRET_PASSWORD_FOR_JWT
    depends_on:
      - pg_db
    restart: always
#database engine service
  pg_db:
    container_name: pg_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=express_db
      - POSTGRES_USER=express_user
      - POSTGRES_PASSWORD=12345 
    volumes:
        #allow *.sql, *.sql.gz, or *.sh and is execute only if data directory is empty
      - pg_db_data:/var/lib/postgresql/data

volumes:
  pg_db_data: {}
